### ISSUE TITLE
Deep copy instance appears to use different instance of enum classes than JVM

### ISSUE THREAD

**Issue by chlacher** [kostaskougios/cloning#86] opened 2019-07-31 19:09 UTC
Certain enums run into equality limbo when undergoing serialization/deserialization across separate instances, which is also observed when using the Cloner class. An example of this is Java Concurrent Library's TimeUnit:

```java
import java.util.concurrent.TimeUnit;
import com.rits.cloning.Cloner;

private static class ClassWithEnum {
    TimeUnit timeUnit;
}

public static void main(String[] args) {
    final Cloner cloner = new Cloner();
    ClassWithEnum a = new ClassWithEnum();
    a.timeUnit = TimeUnit.SECONDS;
    ClassWithEnum b = cloner.deepClone(a);
    cloner.registerStaticFields(TimeUnit.class);
    ClassWithEnum c = cloner.deepClone(a);
    System.out.println("a.timeUnit == TimeUnit.SECONDS: " + (a.timeUnit == TimeUnit.SECONDS));
    System.out.println("a.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode(): " + (a.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode()));
    System.out.println("b.timeUnit == TimeUnit.SECONDS: " + (b.timeUnit == TimeUnit.SECONDS));
    System.out.println("b.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode(): " + (b.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode()));
    System.out.println("c.timeUnit == TimeUnit.SECONDS:" + (c.timeUnit == TimeUnit.SECONDS));
    System.out.println("c.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode(): " + (c.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode()));
    System.out.println("b.timeUnit.compareTo(TimeUnit.SECONDS) == 0: " + (b.timeUnit.compareTo(TimeUnit.SECONDS) == 0));
    System.out.println("b.timeUnit.name() == TimeUnit.SECONDS.name(): " + (b.timeUnit.name() == TimeUnit.SECONDS.name()));
}

````

> a.timeUnit == TimeUnit.SECONDS: true
a.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode(): true
b.timeUnit == TimeUnit.SECONDS: false
b.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode(): false
c.timeUnit == TimeUnit.SECONDS:true
c.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode(): true
b.timeUnit.compareTo(TimeUnit.SECONDS) == 0: true
b.timeUnit.name() == TimeUnit.SECONDS.name(): true

From what I've read and tested within this code base, registering enums as static fields is safe and mitigates this issue.

To mitigate this on my end, I made a utility that recursively finds all enum fields within a class via reflection and registers them as static fields, such that I can instantiate a static Copier with all enums registered as static for any complex object that could potentially run into this issue. Nevertheless, I've created this issue to track and raise awareness of it.

**Comment by tweimer** [comment] 2020-03-08 17:59
@chlacher Is it still an issue on v1.10.2?

I cannot reproduce it with my machine, output below:

> a.timeUnit == TimeUnit.SECONDS: true
> a.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode(): true
> b.timeUnit == TimeUnit.SECONDS: true
> b.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode(): true
> c.timeUnit == TimeUnit.SECONDS:true
> c.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode(): true
> b.timeUnit.compareTo(TimeUnit.SECONDS) == 0: true
> b.timeUnit.name() == TimeUnit.SECONDS.name(): true

**Comment by ZhenXiongQian** [comment] 2021-07-23 07:52
I don't think this is still an issue.
in my machine:
```
a.timeUnit == TimeUnit.SECONDS: true
a.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode(): true
b.timeUnit == TimeUnit.SECONDS: true
b.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode(): true
c.timeUnit == TimeUnit.SECONDS:true
c.timeUnit.hashCode() == TimeUnit.SECONDS.hashCode(): true
b.timeUnit.compareTo(TimeUnit.SECONDS) == 0: true
b.timeUnit.name() == TimeUnit.SECONDS.name(): true
```

**Comment by ZhenXiongQian** [comment] 2021-07-26 07:13
maybe this issue can be close

**Comment by kostaskougios** [comment] 2021-07-30 20:30
I've added this test which passes:

```
    private static class ClassWithEnum {
        TimeUnit timeUnit;
    }
    public void testClassWithEnum() {
        ClassWithEnum a = new ClassWithEnum();
        a.timeUnit = TimeUnit.SECONDS;
        ClassWithEnum b = cloner.deepClone(a);
        assertSame(TimeUnit.SECONDS,b.timeUnit);
    }
```

So it seems not an issue, closing

**Closed by kostaskougios** 2021-07-30 20:30 UTC
